loadSubOlis=["/home/vfurtula/Documents/Projects/Swanepoel_analysis/data/BareSapphire3b.asc",True]
loadSubFilmOlis=["/home/vfurtula/Documents/Projects/Swanepoel_analysis/data/ek062-4.asc",True]
loadSubFTIR=["",False]
loadSubFilmFTIR=["/home/vfurtula/Documents/Projects/Swanepoel_analysis/data/ek062-4.DPT",False]
fit_linear_spline="linear"
gaussian_factors=[6.5, 1.5, 1.0, 0.0]
gaussian_borders=[0.5, 0.6, 0.8, 1.6, 3.26]
ignore_data_pts=80
corr_slit=2
fit_poly_order=4
fit_poly_ranges=[[0.6, 0.95, 1.5, 2.5],True]
filename="save_to_file"
folder="save_to_folder"
timestr="161205-1516"
save_figs=True
plot_X="eV"